name = "Filter game"
version = "1.0.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Filter World"
id = 1
levels = [
	"src/game/world1/level1.lean",
]

[[worlds]]
name = "Filter Basis World"
id = 2
parents = [1]
levels = [
	"src/game/world2/level1.lean",
	"src/game/world2/level2.lean",
	"src/game/world2/level3.lean",
]

[[worlds]]
name = "Order World"
id = 3
parents = [2]
levels = [
	"src/game/world3/level1.lean",
	"src/game/world3/level2.lean",
	"src/game/world3/level3.lean",
	"src/game/world3/level4.lean",
	"src/game/world3/level5.lean",
]

[[worlds]]
name = "Principal Filter World"
id = 4
parents = [3]
levels = [
	"src/game/world4/level1.lean",
	"src/game/world4/level2.lean",
	"src/game/world4/level3.lean",
	"src/game/world4/level4.lean",
	"src/game/world4/level5.lean",
	"src/game/world4/level6.lean",
	"src/game/world4/level7.lean",
	"src/game/world4/level8.lean",
]

[[worlds]]
name = "Ultrafilter World"
id = 5
parents = [4]
levels = [
	"src/game/world5/level1.lean",
	"src/game/world5/level2.lean",
	"src/game/world5/level3.lean",
	"src/game/world5/level4.lean",
]

[[worlds]]
name = "Topology World"
id = 6
parents = [5]
levels = [
	"src/game/world6/level1.lean",
	"src/game/world6/level2.lean",
	"src/game/world6/level3.lean",
	"src/game/world6/level4.lean",
	"src/game/world6/level5.lean",
]

[[worlds]]
name = "Challenge World"
id = 7
parents = [6]
levels = [
	"src/game/world7/level1.lean",
	"src/game/world7/level2.lean",
	"src/game/world7/level3.lean",
	"src/game/world7/level4.lean",
]