import game.world5.level1 -- hide

open set -- hide

variable {α : Type*} -- hide

/-

# Ultrafilter World

## Level 2 : `ultrafilter.le_of_inf_ne_bot`

Now, it's time to do some amazing puzzles!
Our main goal in the rest of this world: 
Prove `f` is an ultrafilter if and only if `sᶜ ∉ f ↔ s ∈ f for ∀ s`.
To prove this, we need wo show `le_of_inf_ne_bot` first.

Notice that in the lemma below we use the "intersection" of two filters, 
which is not the usual intersection of two filters, 
since the intersection of two filters is not always a filter.
Hence instead, we define "intersection" of two filters as 
the filter generated by intersections of elements of the two filters.
This is defined in Challenge World which will come later,
but I will provide some useful lemmas related to it on the left,
you can directly use these lemmas for now, and do them later.
-/

/- Lemma
'lattice.le_of_inf_eq' may be a good start here.
-/
lemma ultrafilter.le_of_inf_ne_bot (f : ultrafilter α) {g : filter α} 
  (hg : (↑f ⊓ g) ≠ ⊥) : ↑f ≤ g :=
begin
  sorry







end

/- Axiom : lattice.le_of_inf_eq (h : a ⊓ b = a)
a ≤ b
-/