import game.world2.level1 -- hide

open set -- hide

variable {α : Type*} -- hide

namespace filter_basis

/- 

# Filter Basis World

## Level 2 : `filter_basis.filter`

Actually, we can construct filter using filter basis:
The filter f generated by filter base B is te collection of all sets fⱼ such
that Bᵢ ⊆ fⱼ for some Bᵢ ∈ B. 
Let's verify that:
-/

/- Lemma : no side bar
The filter associated to a filter basis.
-/
lemma filter' (B : filter_basis α) : filter α := 
{ sets := {s | ∃ t ∈ B, t ⊆ s},
  univ_sets := 
  begin







    sorry
  end,
  upward_closure := 
  begin







    sorry
  end,
  inter_sets := 
  begin






  
    sorry
  end }


end filter_basis

/-
Congratulations! You have verified the axioms of filters.
Now you can construct a filter using a filter basis B by
`filter_basis.filter B`. I also provide some basic APIs on the left,
please check it out.
-/

/- Axiom : filter_basis.filter (B : filter_basis α)
filter α
-/

/- Axiom : filter_basis.mem_filter_iff (B : filter_basis α) {s : set α}
s ∈ B.filter ↔ ∃ t ∈ B, t ⊆ s
-/

/- Axiom : filter_basis.mem_filter_of_mem (B : filter_basis α) {s : set α}
s ∈ B → s ∈ B.filter
-/