import game.world2.level2 -- hide

open set -- hide

variable {α : Type*} -- hide

/-

# Filter Basis World

## Level 3 : `filter_basis.generated_by_filter_eq`

Next, we can try to prove this lemma:
-/

/- Lemma
The filter generated by a filter is actually itself.
-/
lemma filter_basis.generated_by_filter_eq (f : filter α) :
  filter_basis.filter (filter.as_basis f) = f :=
begin
  sorry











end